apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:
  selector:
    matchLabels:
      name: aplicacao-pod
  template:
    metadata:
      labels:
        name: aplicacao-pod
    spec:
      imagePullSecrets:
        - name: alurasportsfeliperegistry.secret
      containers:
        - name: container-aplicacao-loja
          image: alurasportsfeliperegistry.azurecr.io/loja/aplicacao-loja:v1
          ports:
            - containerPort: 80
