apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-azurefile-premium
spec:
  storageClassName: azurefile-premium
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
